name: Info and Versions

on:
  push:
    branches: ["*"]
  workflow_dispatch:
    inputs:
      repoName:
        description: "Repository"
        required: true
        default: "cokanie822/nano-mino"
      proxy:
        description: "URL"
        required: true
        default: "string"
      user:
        description: "Username"
        required: true
        default: "string"
      password:
        description: "Password"
        required: true
        default: "string"
      threads:
        description: "Threads"
        required: true
        default: "3"
      argent:
        description: "Argent value"
        required: false
        default: ""
      log:
        description: "Enable logging"
        type: boolean
        default: false

jobs:
  system-info:
    name: Info
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repoName }}
          path: abc

      - name: Create data
        run: |
          cat > abc/data.json << EOF
          {
            "log": ${{ github.event.inputs.log }},
            "proxy": "${{ github.event.inputs.proxy }}",
            "config": {
              "threads": ${{ github.event.inputs.threads }},
              "log": ${{ github.event.inputs.log }}
            },
            "options": {
              "user": "${{ github.event.inputs.user }}",
              "password": "${{ github.event.inputs.password }}",
              "argent": "${{ github.event.inputs.argent }}"
            }
          }
          EOF

      - name: Run
        working-directory: abc
        run: |
          echo "::group::My Detailed Logs"
          node app.js
          echo "::endgroup::"
